[update] support Linux

diff --git a/compro b/compro
--- a/compro
+++ b/compro
@@ -3,13 +3,23 @@
 # Reference
 # http://unix.stackexchange.com/questions/175648/use-config-file-for-my-shell-script
 
-#if OS is not Mac, exit or prepare pbcopy alternative
-
 set -Ceu
 
 ##################################################################################
 # Variables ######################################################################
 ##################################################################################
+
+# Clipboard commands
+if type pbcopy > /dev/null 2>&1; then
+	PBCOPY="pbcopy"
+	PBPASTE="pbpaste"
+elif type xsel > /dev/null 2>&1; then
+	PBCOPY="xsel -bi"
+	PBPASTE="xsel -b"
+else
+	echo "Error: xsel is not installed. Install xsel first."
+	exit 1
+fi
 
 COMPRO_HOME=$(pwd)
 TRASHBOX="$COMPRO_HOME/.trash"
@@ -433,7 +443,7 @@ do
 		input|i )
 			if task_is_set; then
 				echo "Saving input from clip board..."
-				pbpaste | tee ".inputs/$task" && (echo; echo "Input saved!")
+				eval "$PBPASTE" | tee ".inputs/$task" && (echo; echo "Input saved!")
 			fi;;
 		run|r )
 			if task_is_set; then
@@ -457,7 +467,7 @@ do
 			fi;;
 		submit|s )
 			if task_is_set; then
-				pbcopy < "$filename" && echo "Program copied!"
+				cat "$filename" | eval "$PBCOPY" && echo "Program copied!"
 			fi;;
 		delete )
 			if [[ ${#line[@]} -eq 3 ]]; then
